export enum ApplicationStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  BOOKED = 'BOOKED',
  TICKETED = 'TICKETED',
  COMPLETED = 'COMPLETED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
  FAILED = 'FAILED',
  SUPPLEMENT = 'SUPPLEMENT',
}
