export enum LogAction {
  CREATE_APPLICATION = 'CREATE_APPLICATION',
  UPDATE_APPLICATION = 'UPDATE_APPLICATION',
  CHANGE_STATUS = 'CHANGE_STATUS',
  CREATE_BOOKING = 'CREATE_BOOKING',
  REQUEST_SUPPLEMENT = 'REQUEST_SUPPLEMENT',
  CANCEL_APPLICATION = 'CANCEL_APPLICATION',
  COMPLETE_APPLICATION = 'COMPLETE_APPLICATION',
}
